import pandas as pd

data = [
    ["1", "Development of Practical Skills in Physics", "1.1", "Practical Skills Assessed in a Written Examination", "1.1.1", "Planning"],
    ["1", "Development of Practical Skills in Physics", "1.1", "Practical Skills Assessed in a Written Examination", "1.1.2", "Implementing"],
    ["1", "Development of Practical Skills in Physics", "1.1", "Practical Skills Assessed in a Written Examination", "1.1.3", "Analysis"],
    ["1", "Development of Practical Skills in Physics", "1.1", "Practical Skills Assessed in a Written Examination", "1.1.4", "Evaluation"],
    ["1", "Development of Practical Skills in Physics", "1.2", "Practical Skills Assessed in the Practical Endorsement", "1.2.1", "Practical skills"],
    ["1", "Development of Practical Skills in Physics", "1.2", "Practical Skills Assessed in the Practical Endorsement", "1.2.2", "Use of apparatus and techniques"],
    ["2", "Foundations of Physics", "2.1", "Physical Quantities and Units", "2.1.1", "Physical quantities"],
    ["2", "Foundations of Physics", "2.1", "Physical Quantities and Units", "2.1.2", "S.I. units"],
    ["2", "Foundations of Physics", "2.2", "Making Measurements and Analysing Data", "2.2.1", "Measurements and uncertainties"],
    ["2", "Foundations of Physics", "2.3", "Nature of Quantities", "2.3.1", "Scalars and vectors"],
    ["3", "Forces and Motion", "3.1", "Motion", "3.1.1", "Kinematics"],
    ["3", "Forces and Motion", "3.1", "Motion", "3.1.2", "Linear motion"],
    ["3", "Forces and Motion", "3.1", "Motion", "3.1.3", "Projectile motion"],
    ["3", "Forces and Motion", "3.2", "Forces in Action", "3.2.1", "Dynamics"],
    ["3", "Forces and Motion", "3.2", "Forces in Action", "3.2.2", "Equilibrium"],
    ["3", "Forces and Motion", "3.2", "Forces in Action", "3.2.3", "Density and pressure"],
    ["3", "Forces and Motion", "3.3", "Work, Energy and Power", "3.3.1", "Work and conservation of energy"],
    ["3", "Forces and Motion", "3.3", "Work, Energy and Power", "3.3.2", "Kinetic and potential energies"],
    ["3", "Forces and Motion", "3.3", "Work, Energy and Power", "3.3.3", "Power"],
    ["3", "Forces and Motion", "3.4", "Newton’s Laws of Motion and Momentum", "3.4.1", "Newton’s laws of motion"],
    ["3", "Forces and Motion", "3.4", "Newton’s Laws of Motion and Momentum", "3.4.2", "Collisions and momentum"],
    ["3", "Forces and Motion", "3.5", "Materials", "3.5.1", "Properties of materials"],
    ["4", "Electrons, Waves and Photons", "4.1", "Charge and Current", "4.1.1", "Circuit symbols"],
    ["4", "Electrons, Waves and Photons", "4.1", "Charge and Current", "4.1.2", "Mean drift velocity"],
    ["4", "Electrons, Waves and Photons", "4.2", "Energy, Power and Resistance", "4.2.1", "Circuit symbols"],
    ["4", "Electrons, Waves and Photons", "4.2", "Energy, Power and Resistance", "4.2.2", "Resistance and resistivity"],
    ["4", "Electrons, Waves and Photons", "4.2", "Energy, Power and Resistance", "4.2.3", "Power"],
    ["4", "Electrons, Waves and Photons", "4.3", "Electrical Circuits", "4.3.1", "Series and parallel circuits"],
    ["4", "Electrons, Waves and Photons", "4.3", "Electrical Circuits", "4.3.2", "Internal resistance"],
    ["4", "Electrons, Waves and Photons", "4.3", "Electrical Circuits", "4.3.3", "Potential dividers"],
    ["4", "Electrons, Waves and Photons", "4.4", "Waves", "4.4.1", "Wave motion"],
    ["4", "Electrons, Waves and Photons", "4.4", "Waves", "4.4.2", "Electromagnetic waves"],
    ["4", "Electrons, Waves and Photons", "4.4", "Waves", "4.4.3", "Interference"],
    ["4", "Electrons, Waves and Photons", "4.4", "Waves", "4.4.4", "Stationary waves"],
    ["4", "Electrons, Waves and Photons", "4.5", "Quantum Physics", "4.5.1", "Photons"],
    ["4", "Electrons, Waves and Photons", "4.5", "Quantum Physics", "4.5.2", "The photoelectric effect"],
    ["4", "Electrons, Waves and Photons", "4.5", "Quantum Physics", "4.5.3", "Wave-particle duality"],
    ["5", "Newtonian World and Astrophysics", "5.1", "Thermal Physics", "5.1.1", "Temperature"],
    ["5", "Newtonian World and Astrophysics", "5.1", "Thermal Physics", "5.1.2", "Solid, liquid and gas"],
    ["5", "Newtonian World and Astrophysics", "5.1", "Thermal Physics", "5.1.3", "Specific heat capacity and specific latent heat"],
    ["5", "Newtonian World and Astrophysics", "5.2", "Circular Motion", "5.2.1", "Kinematics of circular motion"],
    ["5", "Newtonian World and Astrophysics", "5.2", "Circular Motion", "5.2.2", "Centripetal force"],
    ["5", "Newtonian World and Astrophysics", "5.3", "Oscillations", "5.3.1", "Simple harmonic motion"],
    ["5", "Newtonian World and Astrophysics", "5.3", "Oscillations", "5.3.2", "Energy of a simple harmonic oscillator"],
    ["5", "Newtonian World and Astrophysics", "5.3", "Oscillations", "5.3.3", "Damping and resonance"],
    ["5", "Newtonian World and Astrophysics", "5.4", "Astrophysics and Cosmology", "5.4.1", "Gravitational fields"],
    ["5", "Newtonian World and Astrophysics", "5.4", "Astrophysics and Cosmology", "5.4.2", "Stars"],
    ["5", "Newtonian World and Astrophysics", "5.4", "Astrophysics and Cosmology", "5.4.3", "Cosmology"],
    ["6", "Particles and Medical Physics", "6.1", "Capacitors", "6.1.1", "Charge and energy"],
    ["6", "Particles and Medical Physics", "6.2", "Electric Fields", "6.2.1", "Coulomb’s law"],
    ["6", "Particles and Medical Physics", "6.2", "Electric Fields", "6.2.2", "Uniform electric fields"],
    ["6", "Particles and Medical Physics", "6.3", "Electromagnetism", "6.3.1", "Magnetic fields"],
    ["6", "Particles and Medical Physics", "6.3", "Electromagnetism", "6.3.2", "Electromagnetic induction"],
    ["6", "Particles and Medical Physics", "6.4", "Nuclear and Particle Physics", "6.4.1", "The nuclear atom"],
    ["6", "Particles and Medical Physics", "6.4", "Nuclear and Particle Physics", "6.4.2", "Fundamental particles"],
    ["6", "Particles and Medical Physics", "6.4", "Nuclear and Particle Physics", "6.4.3", "Radioactivity"],
    ["6", "Particles and Medical Physics", "6.4", "Nuclear and Particle Physics", "6.4.4", "Fission and fusion"],
    ["6", "Particles and Medical Physics", "6.5", "Medical Imaging", "6.5.1", "X-rays"],
    ["6", "Particles and Medical Physics", "6.5", "Medical Imaging", "6.5.2", "Diagnostic methods in medicine"],
    ["6", "Particles and Medical Physics", "6.5", "Medical Imaging", "6.5.3", "Ultrasound"]
]

df = pd.DataFrame(data, columns=["Module Number", "Module Title", "Sub-heading Code", "Sub-heading Title", "Topic Code", "Topic Title"])
df.to_csv("OCR_A_Level_Physics_Specification.csv", index=False)